---
abstract: 'flexible parameter binding and record fetching'
author:
  - 'Iain Campbell <cpanic@cpan.org>'
build_requires:
  DBD::SQLite: '0'
  DBI: '0'
  JSON::Syck: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-FlexibleBinding
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  List::MoreUtils: '0'
  MRO::Compat: '0'
  Scalar::Util: '0'
  namespace::clean: '0'
  perl: '5.006'
resources:
  repository: https://github.com/cpanic/Params-Callbacks.git
version: '0.001001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
