---
abstract: 'Flexible parameter binding and record fetching'
author:
  - 'Iain Campbell <cpanic@cpan.org>'
build_requires:
  Data::Dumper: '0'
  JSON: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-FlexibleBinding
requires:
  Carp: '0'
  DBI: '0'
  Exporter: '0'
  List::MoreUtils: '0'
  MRO::Compat: '0'
  Params::Callbacks: '0'
  Scalar::Util: '0'
  Sub::Name: '0'
  Test::More: '0'
  YAML::Syck: '0'
  namespace::clean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '1.152491'
