---
abstract: 'Greater statement placeholder and data-binding flexibility.'
author:
  - 'Iain Campbell <cpanic@cpan.org>'
build_requires:
  DBD::CSV: '0'
  DBD::SQLite: '0'
  DBD::mysql: '0'
  Data::Dumper::Concise: '0'
  JSON: '0'
  perl: v5.8.8
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-FlexibleBinding
requires:
  DBI: '0'
  List::MoreUtils: '0'
  MRO::Compat: '0'
  Message::String: '0'
  Params::Callbacks: '0'
  Sub::Util: '0'
  namespace::clean: '0'
  perl: v5.8.8
version: 2.0.4
